### ISSUE TITLE
Errors while trying to do "vapor run"

### ISSUE THREAD

**Issue by SheLikesPigs** [CSAllenISDClassroom/sudokuserver-team-howard-1#2]
![sudoku-board-errors](https://user-images.githubusercontent.com/54444559/135915827-5787bb45-69d9-4f21-9de9-61f56c5b2c8e.PNG)

This is probably occurring as a result of unresolved git merge conflicts.

**Comment by Jhews6** [comment]
This was a result of merging conflicts fixed errors 👍
